<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
      
     .row{
        display:flex;
        /*flex-wrap:wrap;*/
       
     }
     /*.container{
        max-width: 1170px;
        margin:auto;
     }*/
     .left{
        width: 25px;/*fkola div sgher kat7ded lk shhal mn ligne baghi*/
        padding:0 105px;/*masafa mabin div o div*/
     }
    </style>
</head>
<body>
  <div class="container">
      <div class="row">
        <div class="left">
          <p>lahfdk kolshi bekher</p>
        </div>
        <div class="left">
        <p>mervi bcp sahbi zwin</p>
        </div>
        <div class="left">
        <p>hania akhouya l3ziiiiiiiiiiiz</p>
        </div>
      </div>
    </div>
    <?php
    echo'<img src="efficace/anim.jpg"';
    ?>
</body>
</html>